// Mocks generated by Mockito 5.4.6 from annotations
// in ardennes/test/features/home_screen/integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ardennes/features/home_screen/bloc.dart' as _i4;
import 'package:ardennes/features/home_screen/event.dart' as _i6;
import 'package:ardennes/features/home_screen/state.dart' as _i2;
import 'package:ardennes/libraries/account_context/bloc.dart' as _i8;
import 'package:ardennes/libraries/account_context/event.dart' as _i10;
import 'package:ardennes/libraries/account_context/state.dart' as _i3;
import 'package:ardennes/models/projects/project_metadata.dart' as _i9;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;


class _FakeHomeScreenState_0 extends _i1.SmartFake
    implements _i2.HomeScreenState {
  _FakeHomeScreenState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountContextState_1 extends _i1.SmartFake
    implements _i3.AccountContextState {
  _FakeAccountContextState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class MockHomeScreenBloc extends _i1.Mock implements _i4.HomeScreenBloc {
  MockHomeScreenBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeScreenState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomeScreenState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.HomeScreenState);

  @override
  _i5.Stream<_i2.HomeScreenState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.HomeScreenState>.empty(),
      ) as _i5.Stream<_i2.HomeScreenState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.HomeScreenEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.HomeScreenEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.HomeScreenState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.HomeScreenEvent>(
    _i7.EventHandler<E, _i2.HomeScreenState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i6.HomeScreenEvent, _i2.HomeScreenState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i2.HomeScreenState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AccountContextBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountContextBloc extends _i1.Mock
    implements _i8.AccountContextBloc {
  MockAccountContextBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.ProjectMetadata> get projects => (super.noSuchMethod(
        Invocation.getter(#projects),
        returnValue: <_i9.ProjectMetadata>[],
      ) as List<_i9.ProjectMetadata>);

  @override
  set projects(List<_i9.ProjectMetadata>? _projects) => super.noSuchMethod(
        Invocation.setter(
          #projects,
          _projects,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AccountContextState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAccountContextState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AccountContextState);

  @override
  _i5.Stream<_i3.AccountContextState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.AccountContextState>.empty(),
      ) as _i5.Stream<_i3.AccountContextState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i9.ProjectMetadata?> loadSelectedProject() => (super.noSuchMethod(
        Invocation.method(
          #loadSelectedProject,
          [],
        ),
        returnValue: _i5.Future<_i9.ProjectMetadata?>.value(),
      ) as _i5.Future<_i9.ProjectMetadata?>);

  @override
  void add(_i10.AccountContextEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i10.AccountContextEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.AccountContextState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i10.AccountContextEvent>(
    _i7.EventHandler<E, _i3.AccountContextState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i10.AccountContextEvent, _i3.AccountContextState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.AccountContextState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
